### ISSUE TITLE
Problems installing PyIGRA

### ISSUE THREAD

**Issue by srbrodzik** [retostauffer/PyIGRA#1]
I downloaded the PyIGRA code and tried to install it but got an error that I don't know what to do with.  Here's the output I got.  The error's at the bottom.

Thanks for your help.

Stacy

rocinante:/usr/local/lib/python2.7/dist-packages/PyIGRA# python setup.py install
/usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'czip_safe'
  warnings.warn(msg)
/usr/lib/python2.7/dist-packages/setuptools/dist.py:333: UserWarning: Normalizing '0.2-0' to '0.2.post0'
  normalized_version,
running install
running bdist_egg
running egg_info
creating PyIGRA.egg-info
writing requirements to PyIGRA.egg-info/requires.txt
writing PyIGRA.egg-info/PKG-INFO
writing top-level names to PyIGRA.egg-info/top_level.txt
writing dependency_links to PyIGRA.egg-info/dependency_links.txt
writing manifest file 'PyIGRA.egg-info/SOURCES.txt'
reading manifest file 'PyIGRA.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'PyIGRA.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib.linux-x86_64-2.7
creating build/lib.linux-x86_64-2.7/PyIGRA
copying PyIGRA/Config.py -> build/lib.linux-x86_64-2.7/PyIGRA
copying PyIGRA/IGRAlibrary.py -> build/lib.linux-x86_64-2.7/PyIGRA
copying PyIGRA/__init__.py -> build/lib.linux-x86_64-2.7/PyIGRA
creating build/lib.linux-x86_64-2.7/PyIGRA/config
copying PyIGRA/config/default.conf -> build/lib.linux-x86_64-2.7/PyIGRA/config
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/PyIGRA
copying build/lib.linux-x86_64-2.7/PyIGRA/Config.py -> build/bdist.linux-x86_64/egg/PyIGRA
copying build/lib.linux-x86_64-2.7/PyIGRA/IGRAlibrary.py -> build/bdist.linux-x86_64/egg/PyIGRA
copying build/lib.linux-x86_64-2.7/PyIGRA/__init__.py -> build/bdist.linux-x86_64/egg/PyIGRA
creating build/bdist.linux-x86_64/egg/PyIGRA/config
copying build/lib.linux-x86_64-2.7/PyIGRA/config/default.conf -> build/bdist.linux-x86_64/egg/PyIGRA/config
byte-compiling build/bdist.linux-x86_64/egg/PyIGRA/Config.py to Config.pyc
byte-compiling build/bdist.linux-x86_64/egg/PyIGRA/IGRAlibrary.py to IGRAlibrary.pyc
byte-compiling build/bdist.linux-x86_64/egg/PyIGRA/__init__.py to __init__.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
installing scripts to build/bdist.linux-x86_64/egg/EGG-INFO/scripts
running install_scripts
running build_scripts
creating build/scripts-2.7
copying and adjusting bin/PyIGRA -> build/scripts-2.7
copying and adjusting bin/PyIGRA_search -> build/scripts-2.7
changing mode of build/scripts-2.7/PyIGRA from 644 to 755
changing mode of build/scripts-2.7/PyIGRA_search from 644 to 755
creating build/bdist.linux-x86_64/egg/EGG-INFO/scripts
copying build/scripts-2.7/PyIGRA -> build/bdist.linux-x86_64/egg/EGG-INFO/scripts
copying build/scripts-2.7/PyIGRA_search -> build/bdist.linux-x86_64/egg/EGG-INFO/scripts
changing mode of build/bdist.linux-x86_64/egg/EGG-INFO/scripts/PyIGRA to 755
changing mode of build/bdist.linux-x86_64/egg/EGG-INFO/scripts/PyIGRA_search to 755
copying PyIGRA.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying PyIGRA.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying PyIGRA.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying PyIGRA.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying PyIGRA.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
PyIGRA.Config: module references __file__
creating dist
creating 'dist/PyIGRA-0.2.post0-py2.7.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing PyIGRA-0.2.post0-py2.7.egg
creating /usr/local/lib/python2.7/dist-packages/PyIGRA-0.2.post0-py2.7.egg
Extracting PyIGRA-0.2.post0-py2.7.egg to /usr/local/lib/python2.7/dist-packages
Adding PyIGRA 0.2.post0 to easy-install.pth file
Installing PyIGRA script to /usr/local/bin
Installing PyIGRA_search script to /usr/local/bin

Installed /usr/local/lib/python2.7/dist-packages/PyIGRA-0.2.post0-py2.7.egg
Processing dependencies for PyIGRA==0.2.post0
Searching for ConfigParser
Reading https://pypi.python.org/simple/ConfigParser/
Downloading https://files.pythonhosted.org/packages/e5/7c/d4ccbcde76b4eea8cbd73b67b88c72578e8b4944d1270021596e80b13deb/configparser-5.0.0.tar.gz#sha256=2ca44140ee259b5e3d8aaf47c79c36a7ab0d5e94d70bd4105c03ede7a20ea5a1
Best match: configparser 5.0.0
Processing configparser-5.0.0.tar.gz
Writing /tmp/easy_install-5PcC_x/configparser-5.0.0/setup.cfg
Running configparser-5.0.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-5PcC_x/configparser-5.0.0/egg-dist-tmp-J98qab
error: Setup script exited with error: 'egg_base' must be a directory name (got `src`)

**Comment by retostauffer** [comment]
Hy Stacy

Thanks for asking. I was going trough your log file and found some smaller things to improve my setup.py (to remove some warnings) but I am not 100% sure what causes the error on your side.

Extended my CI to a series of additional python versions, all automated checks pass and do not cause any problems, see:

<https://travis-ci.org/github/retostauffer/PyIGRA>

Seems you are using easy_install on a Linux system. Ive also tried to use easy_install (python2.7/python3.7) without any problems on my side. Alternatively, try "`python setup.py install`" (or `sudo python setup.py install` depending on your setup) as easy_install will be removed anyways in the future.

In case you are still running into an error can you send me the new error log and maybe also the command you executed, plus some information which Linux distribution and python version you use to narrow down the problem?

All best,
R

**Comment by srbrodzik** [comment]
Thanks for responding.  Our system administrator was able to get this
working but I'm not sure what correction he made.

Stacy

**Comment by retostauffer** [comment]
Thanks for reporting, glad it works :). I'll close this issue, feel free to ask in case you have further questions.

All best,
R
